name: " Bug Report"
description: 提交一个问题 
title: "[Bug]: "
labels: ["bug"]
assignees:
  - Kuingsmile
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |+
        ## PicHoro Bug Report 模板

        请依照该模板来提交，否则将会被关闭。

  - type: input
    id: version
    attributes:
      label: PicHoro的版本 
      placeholder: 例如 V1.8.3
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: 系统信息 
      placeholder: 例如 ViVo X60 Pro
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 问题重现 | Bug reproduce
      description: 请复述Bug重现流程 
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: 相关日志 | Logs
      description: 请附上 PicHoro 的相关报错日志（用文本的形式）。报错日志可以在 PicHoro 设置 -> 软件日志 后右上角导出到剪贴板和本地文件。
  - type: markdown
    attributes:
      value: |
        最后，喜欢 PicHoro 的话不妨给它点个 star~
        